# Generated by Django 4.0.5 on 2023-09-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccrualReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=10, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "date_of_start_period",
                    models.DateTimeField(verbose_name="Дата начала периода"),
                ),
                (
                    "date_of_end_period",
                    models.DateTimeField(verbose_name="Дата конца периода"),
                ),
                ("total", models.FloatField(default=0, verbose_name="Всего")),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.IntegerField()),
                ("contract_counterparty", models.CharField(max_length=200)),
                ("contract", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="PurchasedEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        verbose_name="Наименование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Покупное оборудование",
                "verbose_name_plural": "Покупные оборудования",
            },
        ),
        migrations.CreateModel(
            name="SimCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=10, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "contract",
                    models.CharField(max_length=200, verbose_name="Договор"),
                ),
                (
                    "fio",
                    models.CharField(
                        max_length=100, null=True, verbose_name="ФИО"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Эл. почта"
                    ),
                ),
                (
                    "rate",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Тариф"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        max_length=100,
                        null=True,
                        verbose_name="Серийный номер",
                    ),
                ),
                (
                    "spending_threshold",
                    models.CharField(
                        max_length=200,
                        null=True,
                        verbose_name="Порог расходов (с НДС)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Активный", "Активный"),
                            ("Заблокированный", "Заблокированный"),
                        ],
                        default="Активный",
                        max_length=200,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        null=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        null=True, verbose_name="Дата активации"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Router",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("router_user_id", models.IntegerField()),
                ("total", models.FloatField(null=True)),
                ("note", models.CharField(max_length=500, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="router_table.contract",
                    ),
                ),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="router_table.purchasedequipment",
                    ),
                ),
                (
                    "sim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="router_table.simcard",
                    ),
                ),
            ],
        ),
    ]
