# Generated by Django 4.0.5 on 2023-09-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_object_assembly_details"),
        ("router_table", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="router",
            name="router",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.accounting_for_purchased_equipment",
            ),
        ),
        migrations.DeleteModel(
            name="PurchasedEquipment",
        ),
    ]
