# Generated by Django 4.0.5 on 2023-09-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router_table", "0002_alter_router_router_delete_purchasedequipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="router",
            name="router_user_id",
            field=models.BigIntegerField(),
        ),
    ]
