# Generated by Django 4.0.5 on 2023-09-07 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("router_table", "0003_alter_router_router_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Antenna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Антенна"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contract",
            name="short_name",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Короткое название"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract",
            field=models.CharField(max_length=200, verbose_name="Договор"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract_counterparty",
            field=models.CharField(max_length=200, verbose_name="Контрагент"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract_id",
            field=models.IntegerField(verbose_name="ID"),
        ),
        migrations.AddField(
            model_name="router",
            name="antenna",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="router_table.antenna",
            ),
        ),
    ]
