# Generated by Django 4.0.5 on 2023-09-07 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "router_table",
            "0004_antenna_contract_short_name_alter_contract_contract_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="antenna",
            name="connect",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="antenna",
            name="is_monitoring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="antenna",
            name="power_supply",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
