# Generated by Django 4.0.5 on 2023-09-08 14:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_object_assembly_details"),
        (
            "router_table",
            "0005_antenna_connect_antenna_is_monitoring_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Станция"),
                ),
                (
                    "connect",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "power_supply",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_monitoring", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="router",
            name="antenna",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="antenna",
                to="main.accounting_for_purchased_equipment",
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="router",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="router",
                to="main.accounting_for_purchased_equipment",
            ),
        ),
        migrations.DeleteModel(
            name="Antenna",
        ),
        migrations.AddField(
            model_name="router",
            name="station",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="router_table.station",
                verbose_name="Станция",
            ),
        ),
    ]
