# Generated by Django 4.2.6 on 2023-10-25 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_contractstatus"),
        ("router_table", "0007_contract_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="router",
            name="antenna",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="antenna",
                to="main.accounting_for_purchased_equipment",
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="note",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="router",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="router_table.station",
                verbose_name="Станция",
            ),
        ),
    ]
