# Generated by Django 4.2.6 on 2023-11-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "router_table",
            "0008_alter_router_antenna_alter_router_note_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="router",
            name="sim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routers",
                to="router_table.simcard",
            ),
        ),
    ]
