# Generated by Django 4.2.6 on 2023-11-29 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_object_assembly_unit_object_assembly_under_the_node"),
        ("router_table", "0009_alter_router_sim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="router",
            name="router",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="router",
                to="main.accounting_for_purchased_equipment",
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="router_user_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="router",
            name="total",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
