# Generated by Django 4.2.4 on 2023-09-26 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="accounting_of_services_and_equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        verbose_name="Наименование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуги и оборудования",
                "verbose_name_plural": "Услуги и оборудования",
            },
        ),
        migrations.CreateModel(
            name="SubServiceOrEquipmentUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equip_services.accounting_of_services_and_equipment",
                    ),
                ),
            ],
        ),
    ]
