# Generated by Django 4.2.4 on 2023-09-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("equip_services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subserviceorequipmentunit",
            name="name",
            field=models.CharField(
                default="", max_length=200, verbose_name="Наименование"
            ),
        ),
        migrations.AlterField(
            model_name="subserviceorequipmentunit",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="equip_services.accounting_of_services_and_equipment",
            ),
        ),
    ]
