# Generated by Django 4.2.6 on 2023-10-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "equip_services",
            "0003_accounting_of_services_and_equipment_parent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accounting_of_services_and_equipment",
            name="see_id",
            field=models.CharField(default="", max_length=20),
        ),
    ]
