# Generated by Django 4.0.5 on 2023-08-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("a_key", models.CharField(max_length=20)),
                ("user_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("family_name", models.CharField(max_length=100)),
                ("access", models.IntegerField(default=0)),
                ("tel", models.CharField(max_length=20, null=True)),
                ("birthday", models.DateTimeField(null=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "position_at_work",
                    models.CharField(max_length=150, null=True),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
