# Generated by Django 4.0.5 on 2023-08-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "employee_cards",
            "0002_counterparty_alter_employee_options_employee_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="counterparty",
            name="title",
            field=models.CharField(max_length=300),
        ),
    ]
