# Generated by Django 4.0.5 on 2023-08-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_cards", "0003_alter_counterparty_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="_custom_path"
            ),
        ),
    ]
