# Generated by Django 4.0.5 on 2023-08-18 13:56

from django.db import migrations, models
import employee_cards.models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_cards", "0004_alter_employee_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["family_name"],
                "verbose_name": "карточку сотрудника",
                "verbose_name_plural": "Карточки сотрудников",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="mail",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("Основная работа", "Основная работа"),
                    ("Сдельно", "Сдельно"),
                    ("Частичная занятость", "Частичная занятость"),
                ],
                default="Основная работа",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=employee_cards.models.custom_path,
            ),
        ),
    ]
