# Generated by Django 4.0.5 on 2023-08-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "employee_cards",
            "0005_alter_employee_options_employee_mail_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_dismissed",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
