# Generated by Django 4.0.5 on 2023-09-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_cards", "0009_alter_counterparty_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counterparty",
            name="tel",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
