# Generated by Django 4.0.5 on 2023-09-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_cards", "0010_alter_counterparty_tel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counterparty",
            name="description",
            field=models.CharField(max_length=305, null=True),
        ),
        migrations.AlterField(
            model_name="counterparty",
            name="group_k",
            field=models.CharField(
                choices=[
                    ("Поставщики", "Поставщики"),
                    ("Государственные органы", "Государственные органы"),
                    ("Покупатели", "Покупатели"),
                    ("Проблемные поставщики", "Проблемные поставщики"),
                ],
                default="",
                max_length=302,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="counterparty",
            name="title",
            field=models.CharField(max_length=301),
        ),
        migrations.AlterField(
            model_name="counterparty",
            name="trade_name",
            field=models.CharField(max_length=304, null=True),
        ),
        migrations.AlterField(
            model_name="counterparty",
            name="type_k",
            field=models.CharField(
                choices=[
                    ("Юридическое лицо", "Юридическое лицо"),
                    ("Физическое лицо", "Физическое лицо"),
                ],
                default="",
                max_length=303,
                null=True,
            ),
        ),
    ]
