# Generated by Django 4.2.6 on 2023-10-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_cards", "0013_alter_counterparty_inn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counterparty",
            name="description",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="counterparty",
            name="tel",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="counterparty",
            name="trade_name",
            field=models.CharField(blank=True, max_length=304, null=True),
        ),
        migrations.AlterField(
            model_name="counterparty",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
