# Generated by Django 4.2.6 on 2023-10-25 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employee_cards", "0014_alter_counterparty_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="birthday",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="citizenship",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_of_issue",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="issuing_authority",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="mail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization",
                to="employee_cards.counterparty",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position_at_work",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="second_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_organization",
                to="employee_cards.counterparty",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="series_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="tel",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="verified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
