# Generated by Django 4.2.6 on 2023-11-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "employee_cards",
            "0015_alter_employee_address_alter_employee_birthday_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="counterparty",
            name="load_by_month",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="counterparty",
            name="standart_deviation",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
