# Generated by Django 4.2.6 on 2023-11-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employee_cards", "0016_counterparty_load_by_month_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_price", models.FloatField()),
                ("max_price", models.FloatField()),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_cards.counterparty",
                    ),
                ),
            ],
        ),
    ]
