# Generated by Django 4.2.6 on 2023-11-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_cards", "0017_pricechangelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricechangelog",
            name="nomenclature",
            field=models.TextField(default=""),
        ),
    ]
