# Generated by Django 4.2.6 on 2023-11-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_cards", "0018_pricechangelog_nomenclature"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricechangelog",
            name="amount",
            field=models.IntegerField(default=1),
        ),
    ]
