# Generated by Django 4.2.6 on 2023-11-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employee_cards", "0019_pricechangelog_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterpartyInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("nomenclature", models.TextField(default="")),
                ("total", models.FloatField()),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_cards.counterparty",
                    ),
                ),
            ],
        ),
    ]
