# Generated by Django 4.2.6 on 2023-11-04 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employee_cards", "0020_counterpartyinvoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counterpartyinvoice",
            name="counterparty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="employee_cards.counterparty",
            ),
        ),
    ]
