# Generated by Django 4.2.6 on 2023-11-05 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee_cards", "0021_alter_counterpartyinvoice_counterparty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="counterparty",
            old_name="standart_deviation",
            new_name="standard_deviation",
        ),
    ]
