# Generated by Django 4.2.6 on 2023-11-07 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "employee_cards",
            "0022_rename_standart_deviation_counterparty_standard_deviation",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricechangelog",
            name="counterparty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changing_logs",
                to="employee_cards.counterparty",
            ),
        ),
    ]
