# Generated by Django 4.2.6 on 2023-11-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_cards", "0024_alter_counterparty_load_by_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counterparty",
            name="total",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
