# Generated by Django 4.2.6 on 2023-12-01 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employee_cards", "0025_alter_counterparty_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterpartyAliases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField()),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="employee_cards.counterparty",
                    ),
                ),
            ],
        ),
    ]
