version: "3.9"

services:
  db:
    image: postgres
    container_name: ivea-postgres
    env_file:
      - .env.development
    volumes:
        - postgresql-data:/var/lib/postgresql/data
    ports:
        - "5435:5432"
  app:
    build: .
    container_name: ivea-django
    ports:
      - "8008:8000"
    env_file:
      - .env.development
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    depends_on:
      - db
    tty: true
    stdin_open: true
  pgadmin:
    image: dpage/pgadmin4
    container_name: ivea-pgadmin
    depends_on:
      - db
    ports:
      - "5051:80"
    env_file:
      - .env.development

volumes:
    postgresql-data:
