# Generated by Django 4.0.5 on 2023-09-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial_statements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="total",
            field=models.FloatField(null=True, verbose_name="Сумма"),
        ),
    ]
