# Generated by Django 4.2.6 on 2023-10-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial_statements", "0002_report_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="date",
            field=models.DateTimeField(null=True, verbose_name="Дата"),
        ),
        migrations.AddField(
            model_name="report",
            name="mileage",
            field=models.FloatField(null=True, verbose_name="Пробег"),
        ),
    ]
