# Generated by Django 4.2.6 on 2023-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial_statements", "0003_report_date_report_mileage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="mileage",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Пробег"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="note",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Примечание",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="total",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Сумма"
            ),
        ),
    ]
