# Generated by Django 4.2.6 on 2023-10-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_number",
                    models.BigIntegerField(verbose_name="Номер документа"),
                ),
                ("doc_date", models.DateField(verbose_name="Дата документа")),
                (
                    "operation_date",
                    models.DateField(verbose_name="Дата операции"),
                ),
                ("name", models.CharField(verbose_name="Наименование")),
                ("account", models.CharField(verbose_name="Счёт")),
                ("inn", models.CharField(verbose_name="ИНН Контрагента")),
                ("bank", models.CharField(verbose_name="Банк")),
                (
                    "debiting_sum",
                    models.FloatField(
                        null=True, verbose_name="Дебет (Списание) сумма"
                    ),
                ),
                (
                    "credit_sum",
                    models.FloatField(
                        null=True, verbose_name="Кредит (Поступление) сумма"
                    ),
                ),
                (
                    "appointment",
                    models.TextField(
                        verbose_name="Основание операции (назначение платежа)"
                    ),
                ),
            ],
        ),
    ]
