# Generated by Django 4.0.5 on 2022-07-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounting_for_purchased_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Покупное оборудование',
                'verbose_name_plural': 'Покупные оборудования',
            },
        ),
        migrations.CreateModel(
            name='accounting_of_services_and_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Услуги и оборудования',
                'verbose_name_plural': 'Услуги и оборудования',
            },
        ),
        migrations.CreateModel(
            name='assembly_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Сборочная единица',
                'verbose_name_plural': 'Сборочные единицы',
            },
        ),
        migrations.CreateModel(
            name='under_the_node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Подузел',
                'verbose_name_plural': 'Подузлы',
            },
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Узел',
                'verbose_name_plural': 'Узлы',
            },
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='name_purchased', serialize=False, to='main.accounting_for_purchased_equipment', verbose_name='Наименование')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='Ссылка на чертёж')),
            ],
            options={
                'verbose_name': 'деталь',
                'verbose_name_plural': 'детали',
            },
        ),
        migrations.CreateModel(
            name='utn_purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество покупного оборудования(шт.)')),
                ('purchased', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.accounting_for_purchased_equipment', verbose_name='Выбор покупного оборудования')),
                ('under_the_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.under_the_node')),
            ],
        ),
        migrations.CreateModel(
            name='unit_under_the_node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество подузлов(шт.)')),
                ('under_the_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.under_the_node', verbose_name='Выбор подузла')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.unit')),
            ],
        ),
        migrations.CreateModel(
            name='unit_purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество покупного оборудования(шт.)')),
                ('purchased', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.accounting_for_purchased_equipment', verbose_name='Выбор покупного оборудования')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.unit')),
            ],
        ),
        migrations.CreateModel(
            name='object_assembly_purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_assembly', models.IntegerField(db_index=True, verbose_name='object_assembly')),
                ('quantity', models.IntegerField(verbose_name='Количество покупного оборудования(шт.)')),
                ('purchased', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.accounting_for_purchased_equipment', verbose_name='Выбор покупного оборудования')),
            ],
        ),
        migrations.CreateModel(
            name='object_assembly_assembly_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_assembly', models.IntegerField(db_index=True, verbose_name='object_assembly')),
                ('quantity', models.IntegerField(verbose_name='Количество сборочных единиц(шт.)')),
                ('assembly_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.assembly_unit', verbose_name='Выбор сборочной единицы')),
            ],
        ),
        migrations.CreateModel(
            name='assembly_unit_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество узлов(шт.)')),
                ('assembly_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.assembly_unit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.unit', verbose_name='Выбор узла')),
            ],
        ),
        migrations.CreateModel(
            name='assembly_unit_under_the_node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество подузлов(шт.)')),
                ('assembly_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.assembly_unit')),
                ('under_the_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.under_the_node', verbose_name='Выбор подузла')),
            ],
        ),
        migrations.CreateModel(
            name='assembly_unit_purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество покупного оборудования(шт.)')),
                ('assembly_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.assembly_unit')),
                ('purchased', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.accounting_for_purchased_equipment', verbose_name='Выбор покупного оборудования')),
            ],
        ),
        migrations.CreateModel(
            name='accounting_of_services_and_equipment_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_index=True, max_length=500, verbose_name='Описание')),
                ('services', models.ManyToManyField(blank=True, to='main.accounting_of_services_and_equipment', verbose_name='Услуги и оборудования')),
            ],
            options={
                'verbose_name': 'расшифровку услуг или оборудования',
                'verbose_name_plural': 'Расшифровки услуг или оборудования',
            },
        ),
        migrations.CreateModel(
            name='utn_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество деталей(шт.)')),
                ('under_the_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.under_the_node')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.details', verbose_name='Выбор деталей')),
            ],
        ),
        migrations.CreateModel(
            name='unit_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество деталей(шт.)')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.unit')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.details', verbose_name='Выбор деталей')),
            ],
        ),
        migrations.CreateModel(
            name='assembly_unit_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество деталей(шт.)')),
                ('assembly_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.assembly_unit')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.details', verbose_name='Выбор деталей')),
            ],
        ),
    ]
