# Generated by Django 4.0.5 on 2023-08-16 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "main",
            "0002_rename_assembly_unit_assembly_unit_details_belongs_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="object_assembly_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "belongs",
                    models.IntegerField(
                        db_index=True, verbose_name="object_assembly"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        verbose_name="Количество сборочных единиц(шт.)"
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.details",
                        verbose_name="Выбор сборочной единицы",
                    ),
                ),
            ],
        ),
    ]
