# Generated by Django 4.0.5 on 2023-09-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_object_assembly_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.IntegerField()),
                ("open_date", models.DateTimeField()),
                ("close_date", models.DateTimeField(null=True)),
            ],
        ),
    ]
