# Generated by Django 4.2.6 on 2023-11-15 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_contractstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="object_assembly_unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "belongs",
                    models.IntegerField(
                        db_index=True, verbose_name="object_assembly"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(verbose_name="Количество узлов(шт.)"),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.unit",
                        verbose_name="Выбор узла",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="object_assembly_under_the_node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "belongs",
                    models.IntegerField(
                        db_index=True, verbose_name="object_assembly"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        verbose_name="Количество подузлов(шт.)"
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.under_the_node",
                        verbose_name="Выбор подузла",
                    ),
                ),
            ],
        ),
    ]
