# Generated by Django 4.2.6 on 2023-12-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_object_assembly_unit_object_assembly_under_the_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="details",
            name="yandex_file_path",
            field=models.CharField(blank=True),
        ),
    ]
