# Generated by Django 4.2.6 on 2023-12-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_details_yandex_file_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="details",
            name="yandex_file_path",
            field=models.TextField(blank=True),
        ),
    ]
