# Generated by Django 4.2.6 on 2023-12-06 11:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_details_yandex_file_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="details",
            name="yandex_file_path",
        ),
        migrations.AddField(
            model_name="details",
            name="yandex_file_paths",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True),
                blank=True,
                default=[],
                size=None,
            ),
        ),
    ]
