# Generated by Django 4.2.6 on 2023-12-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_projectequipment_object_assembly_project_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assembly_unit_details",
            name="quantity",
            field=models.FloatField(verbose_name="Количество деталей(шт.)"),
        ),
        migrations.AlterField(
            model_name="assembly_unit_purchased",
            name="quantity",
            field=models.FloatField(
                verbose_name="Количество покупного оборудования(шт.)"
            ),
        ),
        migrations.AlterField(
            model_name="assembly_unit_under_the_node",
            name="quantity",
            field=models.FloatField(verbose_name="Количество подузлов(шт.)"),
        ),
        migrations.AlterField(
            model_name="assembly_unit_unit",
            name="quantity",
            field=models.FloatField(verbose_name="Количество узлов(шт.)"),
        ),
        migrations.AlterField(
            model_name="object_assembly_assembly_unit",
            name="quantity",
            field=models.FloatField(
                verbose_name="Количество сборочных единиц(шт.)"
            ),
        ),
        migrations.AlterField(
            model_name="object_assembly_details",
            name="quantity",
            field=models.FloatField(
                verbose_name="Количество сборочных единиц(шт.)"
            ),
        ),
        migrations.AlterField(
            model_name="object_assembly_project_equipment",
            name="quantity",
            field=models.FloatField(verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="object_assembly_purchased",
            name="quantity",
            field=models.FloatField(
                verbose_name="Количество покупного оборудования(шт.)"
            ),
        ),
        migrations.AlterField(
            model_name="object_assembly_under_the_node",
            name="quantity",
            field=models.FloatField(verbose_name="Количество подузлов(шт.)"),
        ),
        migrations.AlterField(
            model_name="object_assembly_unit",
            name="quantity",
            field=models.FloatField(verbose_name="Количество узлов(шт.)"),
        ),
        migrations.AlterField(
            model_name="unit_details",
            name="quantity",
            field=models.FloatField(verbose_name="Количество деталей(шт.)"),
        ),
        migrations.AlterField(
            model_name="unit_purchased",
            name="quantity",
            field=models.FloatField(
                verbose_name="Количество покупного оборудования(шт.)"
            ),
        ),
        migrations.AlterField(
            model_name="unit_under_the_node",
            name="quantity",
            field=models.FloatField(verbose_name="Количество подузлов(шт.)"),
        ),
        migrations.AlterField(
            model_name="utn_details",
            name="quantity",
            field=models.FloatField(verbose_name="Количество деталей(шт.)"),
        ),
        migrations.AlterField(
            model_name="utn_purchased",
            name="quantity",
            field=models.FloatField(
                verbose_name="Количество покупного оборудования(шт.)"
            ),
        ),
    ]
