# Generated by Django 4.2.6 on 2023-12-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_assembly_unit_details_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assembly_unit_details",
            name="unit",
            field=models.CharField(
                default="шт", verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="assembly_unit_purchased",
            name="unit",
            field=models.CharField(
                default="шт", verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="assembly_unit_under_the_node",
            name="unit",
            field=models.CharField(
                default="шт", verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="assembly_unit_unit",
            name="unit",
            field=models.CharField(
                default="шт", verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="object_assembly_assembly_unit",
            name="unit",
            field=models.CharField(
                default="шт", verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="object_assembly_details",
            name="unit",
            field=models.CharField(
                default="шт", verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="object_assembly_project_equipment",
            name="unit",
            field=models.CharField(
                default="шт", verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="object_assembly_purchased",
            name="unit",
            field=models.CharField(
                default="шт", verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="object_assembly_under_the_node",
            name="unit",
            field=models.CharField(
                default="шт", verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="object_assembly_unit",
            name="unit",
            field=models.CharField(
                default="шт", verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="unit_details",
            name="unit",
            field=models.CharField(
                default="шт", verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="unit_purchased",
            name="unit",
            field=models.CharField(
                default="шт", verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="unit_under_the_node",
            name="unit",
            field=models.CharField(
                default="шт", verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="utn_details",
            name="unit",
            field=models.CharField(
                default="шт", verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="utn_purchased",
            name="unit",
            field=models.CharField(
                default="шт", verbose_name="Единица измерения"
            ),
        ),
    ]
