# Generated by Django 4.2.6 on 2024-01-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_assembly_unit_details_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectequipment",
            name="name",
            field=models.CharField(),
        ),
    ]
