# Generated by Django 4.2.6 on 2024-02-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RSS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.IntegerField()),
                ("npp", models.FloatField()),
                ("code", models.CharField()),
                ("parent_work_name", models.CharField()),
                ("work_name", models.CharField()),
                ("unit", models.CharField()),
                ("accounting_method", models.CharField(null=True)),
                ("material_consumption_rate", models.FloatField(null=True)),
                ("volume", models.FloatField()),
                ("basic_materials_unit_cost", models.FloatField(null=True)),
                ("smr_unit_cost", models.FloatField(null=True)),
                ("total_unit_cost", models.FloatField(null=True)),
                ("basic_materials_total_cost", models.FloatField(null=True)),
                ("smr_total_cost", models.FloatField(null=True)),
                ("total_total_cost", models.FloatField(null=True)),
                ("note", models.TextField(null=True)),
            ],
        ),
    ]
