# Generated by Django 4.2.6 on 2024-02-27 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RSS",
            new_name="RSSDmitrov",
        ),
    ]
