# Generated by Django 4.2.6 on 2024-02-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_rename_rss_rssdmitrov"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rssdmitrov",
            name="npp",
            field=models.CharField(),
        ),
    ]
