# Generated by Django 4.2.6 on 2024-03-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_remove_rssdmitrov_additional_attributes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssdmitrov",
            name="application_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rssdmitrov",
            name="counterparty_offer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rssdmitrov",
            name="has_distribution_letter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rssdmitrov",
            name="product_on_object",
            field=models.BooleanField(default=False),
        ),
    ]
