# Generated by Django 4.2.6 on 2024-03-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_rssdmitrov_application_submitted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSSDmitrovStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume", models.FloatField()),
                ("submitted_for_approval", models.BooleanField(default=False)),
                ("application_submitted", models.BooleanField(default=False)),
                ("counterparty_offer", models.BooleanField(default=False)),
                (
                    "has_distribution_letter",
                    models.BooleanField(default=False),
                ),
                ("product_on_object", models.BooleanField(default=False)),
                (
                    "rss_dmitrov_row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="documents.rssdmitrov",
                    ),
                ),
            ],
        ),
    ]
