# Generated by Django 4.2.6 on 2024-03-04 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0008_rssdmitrovstage_basic_materials_total_cost_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rssdmitrov",
            name="application_submitted",
        ),
        migrations.RemoveField(
            model_name="rssdmitrov",
            name="counterparty_offer",
        ),
        migrations.RemoveField(
            model_name="rssdmitrov",
            name="has_distribution_letter",
        ),
        migrations.RemoveField(
            model_name="rssdmitrov",
            name="product_on_object",
        ),
        migrations.RemoveField(
            model_name="rssdmitrovstage",
            name="submitted_for_approval",
        ),
    ]
