# Generated by Django 4.2.6 on 2024-03-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0009_remove_rssdmitrov_application_submitted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssdmitrov",
            name="approved_by_supervision",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rssdmitrov",
            name="originals_is_signed",
            field=models.BooleanField(default=False),
        ),
    ]
