# Generated by Django 4.2.6 on 2024-03-04 15:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0010_rssdmitrov_approved_by_supervision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssdmitrov",
            name="originals_is_signed_file_paths",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="rssdmitrov",
            name="submitted_for_approval_file_paths",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
