# Generated by Django 4.2.6 on 2024-03-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0011_rssdmitrov_originals_is_signed_file_paths_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rssdmitrovstage",
            name="unit_material_cost",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="rssdmitrovstage",
            name="unit_smr_cost",
            field=models.FloatField(null=True),
        ),
    ]
