# Generated by Django 4.2.6 on 2024-03-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0012_rssdmitrovstage_unit_material_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssdmitrov",
            name="additional_is_required",
            field=models.BooleanField(default=False),
        ),
    ]
