# Generated by Django 4.2.6 on 2024-03-06 09:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0013_rssdmitrov_additional_is_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssdmitrov",
            name="distribution_letter_file_paths",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="rssdmitrov",
            name="product_on_object_file_paths",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
