# Generated by Django 4.2.6 on 2024-03-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0014_rssdmitrov_distribution_letter_file_paths_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rssdmitrov",
            name="related_rss",
            field=models.ManyToManyField(
                blank=True, to="documents.rssdmitrov"
            ),
        ),
    ]
