# Generated by Django 4.2.6 on 2024-03-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0015_rssdmitrov_related_rss"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssdmitrov",
            name="new_volume",
            field=models.FloatField(null=True),
        ),
    ]
