# Generated by Django 4.2.6 on 2024-03-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0016_rssdmitrov_new_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssdmitrov",
            name="ks_ivea_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rssdmitrov",
            name="ks_pto_flag",
            field=models.BooleanField(default=False),
        ),
    ]
