# Generated by Django 4.2.6 on 2024-03-13 09:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0017_rssdmitrov_ks_ivea_flag_rssdmitrov_ks_pto_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssdmitrov",
            name="pto_ivea_file_paths",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
