# Generated by Django 4.2.6 on 2024-03-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0018_rssdmitrov_pto_ivea_file_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssdmitrov",
            name="ks_ps_flag",
            field=models.BooleanField(default=False),
        ),
    ]
