# Generated by Django 4.2.6 on 2024-03-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0019_rssdmitrov_ks_ps_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssdmitrovstage",
            name="work_name",
            field=models.CharField(null=True),
        ),
    ]
