# Generated by Django 4.2.6 on 2024-03-14 13:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0020_rssdmitrovstage_work_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssdmitrov",
            name="connected_invoices_id_array",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BigIntegerField(),
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
