# Generated by Django 4.2.6 on 2024-03-14 13:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0021_rssdmitrov_connected_invoices_id_array"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rssdmitrov",
            name="connected_invoices_id_array",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BigIntegerField(),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
