# Generated by Django 4.2.6 on 2024-04-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0022_alter_rssdmitrov_connected_invoices_id_array"),
    ]

    operations = [
        migrations.CreateModel(
            name="TKP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_costs_name", models.CharField()),
                ("npp", models.CharField()),
                ("code", models.CharField()),
                ("costs_name", models.CharField()),
                ("contractor_comment", models.CharField(null=True)),
                ("unit", models.CharField(null=True)),
                ("consumption_coefficient", models.FloatField(null=True)),
                ("amount", models.FloatField(null=True)),
                ("material_unit_cost", models.FloatField(null=True)),
                ("smr_unit_cost", models.FloatField(null=True)),
                ("price", models.FloatField(null=True)),
                ("material_total_cost", models.FloatField(null=True)),
                ("smr_total_cost", models.FloatField(null=True)),
                ("total_cost", models.FloatField(null=True)),
            ],
        ),
    ]
