# Generated by Django 4.2.6 on 2023-11-27 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("equip_services", "0004_accounting_of_services_and_equipment_see_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=200, verbose_name="ФИО")),
                (
                    "tel",
                    models.CharField(
                        max_length=200, verbose_name="Номер телефон"
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        max_length=200, verbose_name="Название организации"
                    ),
                ),
                (
                    "mail",
                    models.CharField(max_length=200, verbose_name="Почта"),
                ),
            ],
            options={
                "verbose_name": "контактная информация о заказчике",
                "verbose_name_plural": "контактную информацию о заказчике",
            },
        ),
        migrations.CreateModel(
            name="ContactInformationToServicesEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commercial_offers.contactinformation",
                    ),
                ),
                (
                    "services_equipment",
                    models.ManyToManyField(
                        to="equip_services.accounting_of_services_and_equipment"
                    ),
                ),
            ],
        ),
    ]
