# Generated by Django 4.2.6 on 2024-03-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commercial_offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinformationtoservicesequipment",
            name="cost_with_vat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactinformationtoservicesequipment",
            name="npp",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactinformationtoservicesequipment",
            name="unit_of_measurement",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactinformationtoservicesequipment",
            name="work_name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
