# Generated by Django 4.0.5 on 2023-09-18 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fuel_cards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fuelcard",
            name="card_number",
        ),
    ]
