# Generated by Django 4.2.6 on 2023-12-01 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employee_cards", "0026_counterpartyaliases"),
        ("invoice_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="counterparty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employee_cards.counterparty",
            ),
        ),
    ]
