# Generated by Django 4.2.6 on 2023-12-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_analysis", "0003_invoice_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="entrance",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(blank=True, null=True),
        ),
    ]
