# Generated by Django 4.2.6 on 2024-01-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_analysis", "0005_alter_invoice_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.IntegerField()),
                ("amount", models.FloatField(default=1)),
                (
                    "second_sum",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "vat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoice_analysis.invoice",
                    ),
                ),
            ],
        ),
    ]
